#ifndef CONSTANTS_GLSL
#define CONSTANTS_GLSL

const uint VERTEX_ATTRIB_POS_LOCATION						= 0U;
const uint VERTEX_ATTRIB_TEXCOORD_LOCATION					= 1U;
const uint VERTEX_ATTRIB_NORMAL_LOCATION					= 2U;
const uint VERTEX_ATTRIB_COLOR_LOCATION						= 3U;
const uint VERTEX_ATTRIB_TANGENT_LOCATION					= 4U;

const uint RENDER_TARGET_DESC_SET_LOCATION					= 0U;
// TODO: render target descriptors

const uint SUB_LAYER_DESC_SET_LOCATION						= 1U;

const uint SUB_LAYER_INSTANCE_INFO_LOCATION					= 0U;

const uint SUB_LAYER_MATERIAL_DESC_LOCATION0				= 1U;
const uint SUB_LAYER_MATERIAL_DESC_LOCATION1				= 2U;
const uint SUB_LAYER_MATERIAL_DESC_LOCATION2				= 3U;
const uint SUB_LAYER_MATERIAL_DESC_LOCATION3				= 4U;

const uint SUB_LAYER_MATERIAL_TEXTURE_LUT_DESC_LOCATION0	= 5U;
const uint SUB_LAYER_MATERIAL_TEXTURE_LUT_DESC_LOCATION1	= 6U;
const uint SUB_LAYER_MATERIAL_TEXTURE_LUT_DESC_LOCATION2	= 7U;
const uint SUB_LAYER_MATERIAL_TEXTURE_LUT_DESC_LOCATION3	= 8U;

const uint SUB_LAYER_TEXTURES_LOCATION						= 9U;

#endif