#ifndef SIMPLE_COMMON_GLSL
#define SIMPLE_COMMON_GLSL

#include <Shaders/Constants.glsl>

const uint SIMPLE_MATERIAL_DESC_LOCATION			= SUB_LAYER_MATERIAL_DESC_LOCATION0;
const uint SIMPLE_MATERIAL_TEX_LUT_DESC_LOCATION	= SUB_LAYER_MATERIAL_TEXTURE_LUT_DESC_LOCATION0;

const uint SIMPLE_MATERIAL_SLOT_INDEX				= (SIMPLE_MATERIAL_DESC_LOCATION - SUB_LAYER_MATERIAL_DESC_LOCATION0);
const uint SIMPLE_MATERIAL_TEXTURE_SLOT_COUNT		= 1U;
const uint SIMPLE_MATERIAL_ALBEDO_TEX_SLOT_INDEX	= 0U;

#endif